 services:
  client:
    build: .
    image: maxsloof/basedlibrarian-client
    tty: true
    volumes:
      - ./client:/app/client
      - ./docs:/app/books
      - ./db:/db
      # - ./models:/app/models
    command: python client/main.py
    env_file:
      - .env
    ports:
      - "7860:7860"